services:
  # 1. Elasticsearch (La base de données des logs)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Désactive la sécurité pour simplifier l'exercice local
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" # Limite la RAM 
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # 2. Logstash (Le tuyau qui reçoit et transforme les logs)
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    command: -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./misc/elk/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - app-network
  
  kibana-setup:
    image: curlimages/curl:latest
    container_name: kibana-setup
    volumes:
      - ./misc/elk/kibana/export.ndjson:/tmp/export.ndjson
    networks:
      - app-network
    depends_on:
      kibana:
        condition: service_healthy
    # Ce script attend que Kibana réponde, puis importe le fichier
    entrypoint: 
    - sh
    - -c
    - |
      echo "Attente de la disponibilité de Kibana..."
      # On attend que l'API de statut renvoie un code 200
      until [ "$$(curl -s -o /dev/null -w '%{http_code}' http://kibana:5601/api/status)" -eq 200 ]; do
        echo "Kibana n'est pas encore prêt (503/404)... attente 5s"
        sleep 5
      done
      echo "Kibana est prêt. Importation du dashboard..."
      # La commande curl sur une seule ligne pour éviter les erreurs de parsing
      curl -X POST "http://kibana:5601/api/saved_objects/_import?createNewCopies=true" -H "kbn-xsrf: true" --form "file=@/tmp/export.ndjson"
      echo -e "\nImportation terminée."


  # 3. Kibana (L'interface graphique)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 5

# On utilise le MEME réseau que ton application
networks:
  app-network:
    driver: bridge

volumes:
  es_data: