input {
  # On écoute sur le port 5000 les logs venant de Spring Boot
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  # On envoie tout vers Elasticsearch
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
  # Affiche aussi dans la console de Logstash (pour débugger)
  stdout { codec => rubydebug }
}